In [10]:
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in c:\users\hp\anaconda3\lib\site-packages (4.9.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\hp\anaconda3\lib\site-packages (from beautifulsoup4) (2.2.1)

In [124]:
import pandas as pd
import numpy as np

In [11]:
!pip install google

Requirement already satisfied: google in c:\users\hp\anaconda3\lib\site-packages (3.0.0)
Requirement already satisfied: beautifulsoup4 in c:\users\hp\anaconda3\lib\site-packages (from google) (4.9.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\hp\anaconda3\lib\site-packages (from beautifulsoup4->google) (2.2.1)

In [2]:
try:
    from googlesearch import search
except ImportError:
    print("No module named 'google' found")
 
# to search
query = "ONGC Website Annual Report 2021"
 
for j in search(query, tld="co.in", num=10, stop=10, pause=2):
    print(j)

https://www.ongcindia.com/wps/wcm/connect/en/investors/annual-reports/
https://www.ongcindia.com/wps/wcm/connect/en/investors/annual-reports/archive
https://www.ongcindia.com/wps/wcm/connect/en/about-ongc/performance/financial/Results/
https://www.ongcindia.com/wps/wcm/connect/en/investors/investor-presentation/
https://www.ongcindia.com/
https://www.ongcindia.com/wps/wcm/connect/en/about-ongc/performance/financial/Highlights/
https://www.ongcindia.com/wps/wcm/connect/hi/investors/annual-reports/
https://ongc.co.in/wps/wcm/connect/en/investors/annual-reports/
https://www.moneycontrol.com/financials/oilnaturalgascorporation/balance-sheetVI/ONG
https://economictimes.indiatimes.com/oil-and-natural-gas-corporation-ltd/balancesheet/companyid-11599.cms

In [1]:
!pip install "camelot-py[cv]"

Requirement already satisfied: camelot-py[cv] in c:\users\hp\anaconda3\lib\site-packages (0.10.1)
Requirement already satisfied: tabulate>=0.8.9 in c:\users\hp\anaconda3\lib\site-packages (from camelot-py[cv]) (0.8.9)
Requirement already satisfied: openpyxl>=2.5.8 in c:\users\hp\anaconda3\lib\site-packages (from camelot-py[cv]) (3.0.7)
Requirement already satisfied: click>=6.7 in c:\users\hp\anaconda3\lib\site-packages (from camelot-py[cv]) (7.1.2)
Requirement already satisfied: pdfminer.six>=20200726 in c:\users\hp\anaconda3\lib\site-packages (from camelot-py[cv]) (20211012)
Requirement already satisfied: numpy>=1.13.3 in c:\users\hp\anaconda3\lib\site-packages (from camelot-py[cv]) (1.20.1)
Requirement already satisfied: pandas>=0.23.4 in c:\users\hp\anaconda3\lib\site-packages (from camelot-py[cv]) (1.2.4)
Requirement already satisfied: PyPDF2>=1.26.0 in c:\users\hp\anaconda3\lib\site-packages (from camelot-py[cv]) (1.26.0)
Requirement already satisfied: chardet>=3.0.4 in c:\users\hp\anaconda3\lib\site-packages (from camelot-py[cv]) (4.0.0)
Requirement already satisfied: pdftopng>=0.2.3 in c:\users\hp\anaconda3\lib\site-packages (from camelot-py[cv]) (0.2.3)
Requirement already satisfied: opencv-python>=3.4.2.17 in c:\users\hp\anaconda3\lib\site-packages (from camelot-py[cv]) (4.5.4.58)
Requirement already satisfied: ghostscript>=0.7 in c:\users\hp\anaconda3\lib\site-packages (from camelot-py[cv]) (0.7)
Requirement already satisfied: setuptools>=38.6.0 in c:\users\hp\anaconda3\lib\site-packages (from ghostscript>=0.7->camelot-py[cv]) (52.0.0.post20210125)
Requirement already satisfied: et-xmlfile in c:\users\hp\anaconda3\lib\site-packages (from openpyxl>=2.5.8->camelot-py[cv]) (1.0.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\hp\anaconda3\lib\site-packages (from pandas>=0.23.4->camelot-py[cv]) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\hp\anaconda3\lib\site-packages (from pandas>=0.23.4->camelot-py[cv]) (2021.1)
Requirement already satisfied: cryptography in c:\users\hp\anaconda3\lib\site-packages (from pdfminer.six>=20200726->camelot-py[cv]) (3.4.7)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas>=0.23.4->camelot-py[cv]) (1.15.0)
Requirement already satisfied: cffi>=1.12 in c:\users\hp\anaconda3\lib\site-packages (from cryptography->pdfminer.six>=20200726->camelot-py[cv]) (1.14.5)
Requirement already satisfied: pycparser in c:\users\hp\anaconda3\lib\site-packages (from cffi>=1.12->cryptography->pdfminer.six>=20200726->camelot-py[cv]) (2.20)

In [2]:
import camelot

In [3]:
#tables2=camelot.read_pdf('ONGC-Final_2021.pdf',table_regions=['170,370,560,270'], pages='280-281')

tables2=camelot.read_pdf('ONGC-Final_2021.pdf', flavor='stream', pages='280-281')
tables2

In [4]:
tables2[0]

In [5]:
tables2[1]

In [6]:
print(tables2[0].df)

   0                                                   1  \
0                                        THE UNSTOPPABLE
1                                        ENERGY SOLDIERS
2      11.1.1 \nThe  Company \nhas \nelected \nto \nc...
3      with  the  carrying  value  of  its  investmen...
4
.. ..                                                ...
78           subscribed  10 nos. equity shares of Planys
79
80        Technologies \nPrivate \nLimited \na \nstartup
81
82        Company,  having  face  value  `10  per  share

                                                   2  \
0
1
2         at a premium of  `25,430.00 per share. The
3   equity  shares  have  been  fair  valued  during
4
..                                               ...
78
79   as  fair  valued  through  other  comprehensive
80
81                                  income (FVTOCI).
82

                               3 4  5                                   6  \
0
1
2   11.2 Details of Subsidiaries
3
4                                       Proportion of ownership interest/
..                           ... .. ..                                ...
78
79
80
81
82

                7 8
0   ANNUAL REPORT
1         2020-21
2
3
4
..            ... ..
78
79
80
81
82

[83 rows x 9 columns]

In [7]:
print(tables2[1].df)

   0                                                 1  2  3       4   \
0                                       THE UNSTOPPABLE
1                                       ENERGY SOLDIERS
2                        11.4 Details of Joint Ventures
3
4
.. ..                                               ... .. ..     ...
76
77
78     Aggregate carrying value of unquoted investments        233.90
79
80

                                   5  6       7   \
0
1
2
3
4   Proportion of ownership interest/
..                                ... ..     ...
76
77
78                                        220.69
79
80

                                                   8   \
0
1
2   11.5.1  During \nthe \nyear  2018-19, \nthe  C...
3      had  subscribed \nfor  additional  1,179  nos.
4
..                                                ...
76       Convertible  Preference  Shares \n(CCPS)  of
77  String  Bio  Private  Limited  (SBPL),  a  sta...
78
79       Company,  having \nface  value  of  `10  per
80    share  at  a  premium  of  `267.30  per  share.

                                                   9  10
0                                       ANNUAL REPORT
1                                             2020-21
2       The  CCPS  are  Compulsory  convertible  into
3    equity  shares  upon  the  expiry  of  20  years
4
..                                                ... ..
76
77  11.5.4.  During \nthe \nyear  2019-20, \nthe  ...
78
79          has \nsubscribed  19149  nos.  Compulsory
80       Convertible  Preference  Shares \n(CCPS)  of

[81 rows x 11 columns]

In [4]:
tables2[1].parsing_report

{'accuracy': 94.02, 'whitespace': 78.45, 'order': 1, 'page': 281}

In [5]:
tables2[0].parsing_report

{'accuracy': 94.66, 'whitespace': 76.57, 'order': 1, 'page': 280}

In [6]:
tables2.export('table.csv')

In [7]:
df3=tables2[0].df

In [8]:
df31=df3.iloc[16:34,[3,5,6]]
df31
#add column of subsidiary

                             3                             5        6
16         ONGC Videsh Limited  Incorporated in India having  100.00%
17
18                               all operation outside India
19
20      Mangalore Refinery and                         India   71.63%
21
22      Petrochemicals Limited
23
24
25         Hindustan Petroleum                         India   53.64%
26
27        Corporation Limited*
28
29              ONGC Mangalore                         India
30      Petrochemicals Limited
31           (Note No. 11.1.2)
32
33  Petronet MHB Limited (Note                         India   49.99%

In [9]:
df32=df31.reset_index(drop=True)
df32.head()

                        3                             5        6
0     ONGC Videsh Limited  Incorporated in India having  100.00%
1
2                           all operation outside India
3
4  Mangalore Refinery and                         India   71.63%

In [10]:
df31.columns=["Name of the Company", "Country of Incorporation","Proportion of ownership interest as March 31, 2021"]
df31

,Name of the Company,Country of Incorporation,"Proportion of ownership interest as March 31, 2021"
16,ONGC Videsh Limited,Incorporated in India having,100.00%
17,,,
18,,all operation outside India,
19,,,
20,Mangalore Refinery and,India,71.63%
21,,,
22,Petrochemicals Limited,,
23,,,
24,,,
25,Hindustan Petroleum,India,53.64%
26,,,
27,Corporation Limited*,,
28,,,
29,ONGC Mangalore,India,
30,Petrochemicals Limited,,
31,(Note No. 11.1.2),,
32,,,
33,Petronet MHB Limited (Note,India,49.99%

In [11]:
#concatenate the string

df31['Name of the Company']=df31.groupby(['Country of Incorporation','Proportion of ownership interest as March 31, 2021'])['Name of the Company'].transform(lambda x: ''.join(x))
df31 = df31.drop_duplicates()
df31=df31.reset_index(drop=True)
df31=df31.dropna()
df31

,Name of the Company,Country of Incorporation,"Proportion of ownership interest as March 31, 2021"
0,ONGC Videsh Limited,Incorporated in India having,100.00%
1,Petrochemicals LimitedCorporation Limited*Petr...,,
2,,all operation outside India,
3,Mangalore Refinery and,India,71.63%
4,Hindustan Petroleum,India,53.64%
5,ONGC Mangalore,India,
6,Petronet MHB Limited (Note,India,49.99%

In [16]:
df4=tables2[0].df
df41=df4.iloc[61:69,[3,5,6]]
df41
#add column of associate

                          3      5       6
61       Pawan Hans Limited  India  49.00%
62
63
64    Petronet LNG Limited*  India  12.50%
65
66
67
68  Rohini Heliport Limited  India  49.00%

In [17]:
df42=df41.reset_index(drop=True)

In [18]:
df42.columns=["Name of the Company", "Country of Incorporation","Proportion of ownership interest as March 31, 2021"]
df42

,Name of the Company,Country of Incorporation,"Proportion of ownership interest as March 31, 2021"
0,Pawan Hans Limited,India,49.00%
1,,,
2,,,
3,Petronet LNG Limited*,India,12.50%
4,,,
5,,,
6,,,
7,Rohini Heliport Limited,India,49.00%

In [19]:
#concatenate the string
df42['Proportion of ownership interest as March 31, 2021']=df42.groupby(['Name of the Company','Country of Incorporation'])['Proportion of ownership interest as March 31, 2021'].transform(lambda x: ''.join(x))
df42 = df42.drop_duplicates()

df42=df42.reset_index(drop=True)
df42=df42.dropna()
df42

,Name of the Company,Country of Incorporation,"Proportion of ownership interest as March 31, 2021"
0,Pawan Hans Limited,India,49.00%
1,,,
2,Petronet LNG Limited*,India,12.50%
3,Rohini Heliport Limited,India,49.00%

In [20]:
df6=tables2[1].df
df6.head()

,0,1,2,3,4,5,6,7,8,9,10
0,,THE UNSTOPPABLE,,,,,,,,ANNUAL REPORT,
1,,ENERGY SOLDIERS,,,,,,,,2020-21,
2,,11.4 Details of Joint Ventures,,,,,,,"11.5.1 During \nthe \nyear 2018-19, \nthe C...",The CCPS are Compulsory convertible into,
3,,,,,,,,,"had subscribed \nfor additional 1,179 nos.",equity shares upon the expiry of 20 years,
4,,,,,,Proportion of ownership interest/,,,,,

In [21]:
df6=tables2[1].df
df61=df6.iloc[13:31,[1,2,5]]

In [22]:
df62=df61.reset_index(drop=True)
df62
#add column of joint venture

                                               1      2       5
0   Mangalore SEZ Limited\nSpecial Economic Zone  India  26.00%
1
2                           ONGC Petro Additions
3                                 Petrochemicals  India  49.36%
4                                        Limited
5
6      ONGC Teri Biotech Limited\nBioremediation  India  49.98%
7
8                             ONGC Tripura Power
9                               Power Generation  India  50.00%
10                               Company Limited
11
12
13      Dahej SEZ Limited\nSpecial Economic Zone  India  50.00%
14
15                         Indradhanush Gas Grid
16                                      Pipeline  India  20.00%
17                                       Limited

In [23]:
df62.columns=["Name of the Company", "Country of Incorporation","Proportion of ownership interest as March 31, 2021"]
df62

,Name of the Company,Country of Incorporation,"Proportion of ownership interest as March 31, 2021"
0,Mangalore SEZ Limited\nSpecial Economic Zone,India,26.00%
1,,,
2,ONGC Petro Additions,,
3,Petrochemicals,India,49.36%
4,Limited,,
5,,,
6,ONGC Teri Biotech Limited\nBioremediation,India,49.98%
7,,,
8,ONGC Tripura Power,,
9,Power Generation,India,50.00%
10,Company Limited,,
11,,,
12,,,
13,Dahej SEZ Limited\nSpecial Economic Zone,India,50.00%
14,,,
15,Indradhanush Gas Grid,,
16,Pipeline,India,20.00%
17,Limited,,

In [24]:
#concatenate the string
df62['Proportion of ownership interest as March 31, 2021']=df62.groupby(['Name of the Company','Country of Incorporation'])['Proportion of ownership interest as March 31, 2021'].transform(lambda x: ''.join(x))
df62 = df62.drop_duplicates()

df62=df62.reset_index(drop=True)
df62=df62.dropna()
df62

,Name of the Company,Country of Incorporation,"Proportion of ownership interest as March 31, 2021"
0,Mangalore SEZ Limited\nSpecial Economic Zone,India,26.00%
1,,,
2,ONGC Petro Additions,,
3,Petrochemicals,India,49.36%
4,Limited,,
5,ONGC Teri Biotech Limited\nBioremediation,India,49.98%
6,ONGC Tripura Power,,
7,Power Generation,India,50.00%
8,Company Limited,,
9,Dahej SEZ Limited\nSpecial Economic Zone,India,50.00%
10,Indradhanush Gas Grid,,
11,Pipeline,India,20.00%

In [25]:
df62['Proportion of ownership interest as March 31, 2021']=df62.groupby(['Name of the Company','Country of Incorporation'])['Proportion of ownership interest as March 31, 2021'].transform(lambda x: ''.join(x))
df62 = df62.drop_duplicates()

df62=df62.reset_index(drop=True)
df62=df62.dropna()
df62

,Name of the Company,Country of Incorporation,"Proportion of ownership interest as March 31, 2021"
0,Mangalore SEZ Limited\nSpecial Economic Zone,India,26.00%
1,,,
2,ONGC Petro Additions,,
3,Petrochemicals,India,49.36%
4,Limited,,
5,ONGC Teri Biotech Limited\nBioremediation,India,49.98%
6,ONGC Tripura Power,,
7,Power Generation,India,50.00%
8,Company Limited,,
9,Dahej SEZ Limited\nSpecial Economic Zone,India,50.00%
10,Indradhanush Gas Grid,,
11,Pipeline,India,20.00%

In [154]:
# concat dataframes
df7=pd.concat([df31, df42,df62], axis=0)
df7.head()

,Name of the Company,Country of Incorporation,"Proportion of ownership interest as March 31, 2021"
0,ONGC Videsh Limited,Incorporated in India having,100.00%
1,Petrochemicals LimitedCorporation Limited*Petr...,,
2,,all operation outside India,
3,Mangalore Refinery and,India,71.63%
4,Hindustan Petroleum,India,53.64%

In [33]:
!pip install two-lists-similarity

Collecting two-lists-similarity
  Downloading two_lists_similarity-0.0.5-py3-none-any.whl (6.3 kB)
Installing collected packages: two-lists-similarity
Successfully installed two-lists-similarity-0.0.5

In [106]:
!pip install fuzzywuzzy

Requirement already satisfied: fuzzywuzzy in c:\users\hp\anaconda3\lib\site-packages (0.18.0)

In [155]:
from fuzzywuzzy import fuzz
from fuzzywuzzy import process

In [156]:
match1 = []
match2 = []
k = []

myList1 = df7['Name of the Company'].tolist()
myList2 = df31['Name of the Company'].tolist()

threshold = 100

for i in myList1:
   match1.append(process.extractOne(i, myList2, scorer=fuzz.ratio))
df7['matches'] = match1
for j in df7['matches']:
   if j[1] >= threshold:
    k.append("Yes")
   match2.append("No".join(k))
   k = []



# saving matches to df1 
df7['matches'] = match2 
#df7['Matched subsidiary name'] = match3 
print("\nMatches...")
df7

WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']

Matches...

,Name of the Company,Country of Incorporation,"Proportion of ownership interest as March 31, 2021",matches
0,ONGC Videsh Limited,Incorporated in India having,100.00%,Yes
1,Petrochemicals LimitedCorporation Limited*Petr...,,,Yes
2,,all operation outside India,,Yes
3,Mangalore Refinery and,India,71.63%,Yes
4,Hindustan Petroleum,India,53.64%,Yes
5,ONGC Mangalore,India,,Yes
6,Petronet MHB Limited (Note,India,49.99%,Yes
0,Pawan Hans Limited,India,49.00%,
1,,,,Yes
2,Petronet LNG Limited*,India,12.50%,
3,Rohini Heliport Limited,India,49.00%,
0,Mangalore SEZ Limited\nSpecial Economic Zone,India,26.00%,
1,,,,Yes
2,ONGC Petro Additions,,,
3,Petrochemicals,India,49.36%,
4,Limited,,,
5,ONGC Teri Biotech Limited\nBioremediation,India,49.98%,
6,ONGC Tripura Power,,,
7,Power Generation,India,50.00%,
8,Company Limited,,,
9,Dahej SEZ Limited\nSpecial Economic Zone,India,50.00%,
10,Indradhanush Gas Grid,,,
11,Pipeline,India,20.00%,

In [157]:
match1 = []
match2 = []
k = []

myList1 = df7['Name of the Company'].tolist()
myList2 = df31['Name of the Company'].tolist()

threshold = 100
for i in myList1:
   match1.append(process.extractOne(i, myList2, scorer=fuzz.ratio))
df7['Matched subsidiary name'] = match1
for j in df7['Matched subsidiary name']:
   if j[1] >= threshold:
    k.append(j[0])
   match2.append(",".join(k))
   k = []



# saving matches to df1 
df7['Matched subsidiary name'] = match2 
#df7['Matched subsidiary name'] = match3 
print("\nMatches...")
df7

WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']

Matches...

,Name of the Company,Country of Incorporation,"Proportion of ownership interest as March 31, 2021",matches,Matched subsidiary name
0,ONGC Videsh Limited,Incorporated in India having,100.00%,Yes,ONGC Videsh Limited
1,Petrochemicals LimitedCorporation Limited*Petr...,,,Yes,Petrochemicals LimitedCorporation Limited*Petr...
2,,all operation outside India,,Yes,
3,Mangalore Refinery and,India,71.63%,Yes,Mangalore Refinery and
4,Hindustan Petroleum,India,53.64%,Yes,Hindustan Petroleum
5,ONGC Mangalore,India,,Yes,ONGC Mangalore
6,Petronet MHB Limited (Note,India,49.99%,Yes,Petronet MHB Limited (Note
0,Pawan Hans Limited,India,49.00%,,
1,,,,Yes,
2,Petronet LNG Limited*,India,12.50%,,
3,Rohini Heliport Limited,India,49.00%,,
0,Mangalore SEZ Limited\nSpecial Economic Zone,India,26.00%,,
1,,,,Yes,
2,ONGC Petro Additions,,,,
3,Petrochemicals,India,49.36%,,
4,Limited,,,,
5,ONGC Teri Biotech Limited\nBioremediation,India,49.98%,,
6,ONGC Tripura Power,,,,
7,Power Generation,India,50.00%,,
8,Company Limited,,,,
9,Dahej SEZ Limited\nSpecial Economic Zone,India,50.00%,,
10,Indradhanush Gas Grid,,,,
11,Pipeline,India,20.00%,,

In [158]:
df7=df7.reset_index(drop=True)

In [160]:
df7

,Name of the Company,Country of Incorporation,"Proportion of ownership interest as March 31, 2021",matches,Matched subsidiary name
0,ONGC Videsh Limited,Incorporated in India having,100.00%,Yes,ONGC Videsh Limited
1,Petrochemicals LimitedCorporation Limited*Petr...,,,Yes,Petrochemicals LimitedCorporation Limited*Petr...
2,,all operation outside India,,Yes,
3,Mangalore Refinery and,India,71.63%,Yes,Mangalore Refinery and
4,Hindustan Petroleum,India,53.64%,Yes,Hindustan Petroleum
5,ONGC Mangalore,India,,Yes,ONGC Mangalore
6,Petronet MHB Limited (Note,India,49.99%,Yes,Petronet MHB Limited (Note
7,Pawan Hans Limited,India,49.00%,,
8,,,,Yes,
9,Petronet LNG Limited*,India,12.50%,,
10,Rohini Heliport Limited,India,49.00%,,
11,Mangalore SEZ Limited\nSpecial Economic Zone,India,26.00%,,
12,,,,Yes,
13,ONGC Petro Additions,,,,
14,Petrochemicals,India,49.36%,,
15,Limited,,,,
16,ONGC Teri Biotech Limited\nBioremediation,India,49.98%,,
17,ONGC Tripura Power,,,,
18,Power Generation,India,50.00%,,
19,Company Limited,,,,
20,Dahej SEZ Limited\nSpecial Economic Zone,India,50.00%,,
21,Indradhanush Gas Grid,,,,
22,Pipeline,India,20.00%,,

In [162]:
update_df = df7.drop([8, 12])

,Name of the Company,Country of Incorporation,"Proportion of ownership interest as March 31, 2021",matches,Matched subsidiary name
0,ONGC Videsh Limited,Incorporated in India having,100.00%,Yes,ONGC Videsh Limited
1,Petrochemicals LimitedCorporation Limited*Petr...,,,Yes,Petrochemicals LimitedCorporation Limited*Petr...
2,,all operation outside India,,Yes,
3,Mangalore Refinery and,India,71.63%,Yes,Mangalore Refinery and
4,Hindustan Petroleum,India,53.64%,Yes,Hindustan Petroleum
5,ONGC Mangalore,India,,Yes,ONGC Mangalore
6,Petronet MHB Limited (Note,India,49.99%,Yes,Petronet MHB Limited (Note
7,Pawan Hans Limited,India,49.00%,,
9,Petronet LNG Limited*,India,12.50%,,
10,Rohini Heliport Limited,India,49.00%,,
11,Mangalore SEZ Limited\nSpecial Economic Zone,India,26.00%,,
13,ONGC Petro Additions,,,,
14,Petrochemicals,India,49.36%,,
15,Limited,,,,
16,ONGC Teri Biotech Limited\nBioremediation,India,49.98%,,
17,ONGC Tripura Power,,,,
18,Power Generation,India,50.00%,,
19,Company Limited,,,,
20,Dahej SEZ Limited\nSpecial Economic Zone,India,50.00%,,
21,Indradhanush Gas Grid,,,,
22,Pipeline,India,20.00%,,

In [163]:
update_df.reset_index(drop=True)

,Name of the Company,Country of Incorporation,"Proportion of ownership interest as March 31, 2021",matches,Matched subsidiary name
0,ONGC Videsh Limited,Incorporated in India having,100.00%,Yes,ONGC Videsh Limited
1,Petrochemicals LimitedCorporation Limited*Petr...,,,Yes,Petrochemicals LimitedCorporation Limited*Petr...
2,,all operation outside India,,Yes,
3,Mangalore Refinery and,India,71.63%,Yes,Mangalore Refinery and
4,Hindustan Petroleum,India,53.64%,Yes,Hindustan Petroleum
5,ONGC Mangalore,India,,Yes,ONGC Mangalore
6,Petronet MHB Limited (Note,India,49.99%,Yes,Petronet MHB Limited (Note
7,Pawan Hans Limited,India,49.00%,,
8,Petronet LNG Limited*,India,12.50%,,
9,Rohini Heliport Limited,India,49.00%,,
10,Mangalore SEZ Limited\nSpecial Economic Zone,India,26.00%,,
11,ONGC Petro Additions,,,,
12,Petrochemicals,India,49.36%,,
13,Limited,,,,
14,ONGC Teri Biotech Limited\nBioremediation,India,49.98%,,
15,ONGC Tripura Power,,,,
16,Power Generation,India,50.00%,,
17,Company Limited,,,,
18,Dahej SEZ Limited\nSpecial Economic Zone,India,50.00%,,
19,Indradhanush Gas Grid,,,,
20,Pipeline,India,20.00%,,

In [169]:
update_df['matches']=update_df['matches'].replace(r'^\s*$', np.nan, regex=True)
update_df

,Name of the Company,Country of Incorporation,"Proportion of ownership interest as March 31, 2021",matches,Matched subsidiary name
0,ONGC Videsh Limited,Incorporated in India having,100.00%,Yes,ONGC Videsh Limited
1,Petrochemicals LimitedCorporation Limited*Petr...,,,Yes,Petrochemicals LimitedCorporation Limited*Petr...
2,,all operation outside India,,Yes,
3,Mangalore Refinery and,India,71.63%,Yes,Mangalore Refinery and
4,Hindustan Petroleum,India,53.64%,Yes,Hindustan Petroleum
5,ONGC Mangalore,India,,Yes,ONGC Mangalore
6,Petronet MHB Limited (Note,India,49.99%,Yes,Petronet MHB Limited (Note
7,Pawan Hans Limited,India,49.00%,NaN,
9,Petronet LNG Limited*,India,12.50%,NaN,
10,Rohini Heliport Limited,India,49.00%,NaN,
11,Mangalore SEZ Limited\nSpecial Economic Zone,India,26.00%,NaN,
13,ONGC Petro Additions,,,NaN,
14,Petrochemicals,India,49.36%,NaN,
15,Limited,,,NaN,
16,ONGC Teri Biotech Limited\nBioremediation,India,49.98%,NaN,
17,ONGC Tripura Power,,,NaN,
18,Power Generation,India,50.00%,NaN,
19,Company Limited,,,NaN,
20,Dahej SEZ Limited\nSpecial Economic Zone,India,50.00%,NaN,
21,Indradhanush Gas Grid,,,NaN,
22,Pipeline,India,20.00%,NaN,

In [170]:
update_df['matches'] = update_df['matches'].replace(np.nan, 'No')
update_df

,Name of the Company,Country of Incorporation,"Proportion of ownership interest as March 31, 2021",matches,Matched subsidiary name
0,ONGC Videsh Limited,Incorporated in India having,100.00%,Yes,ONGC Videsh Limited
1,Petrochemicals LimitedCorporation Limited*Petr...,,,Yes,Petrochemicals LimitedCorporation Limited*Petr...
2,,all operation outside India,,Yes,
3,Mangalore Refinery and,India,71.63%,Yes,Mangalore Refinery and
4,Hindustan Petroleum,India,53.64%,Yes,Hindustan Petroleum
5,ONGC Mangalore,India,,Yes,ONGC Mangalore
6,Petronet MHB Limited (Note,India,49.99%,Yes,Petronet MHB Limited (Note
7,Pawan Hans Limited,India,49.00%,No,
9,Petronet LNG Limited*,India,12.50%,No,
10,Rohini Heliport Limited,India,49.00%,No,
11,Mangalore SEZ Limited\nSpecial Economic Zone,India,26.00%,No,
13,ONGC Petro Additions,,,No,
14,Petrochemicals,India,49.36%,No,
15,Limited,,,No,
16,ONGC Teri Biotech Limited\nBioremediation,India,49.98%,No,
17,ONGC Tripura Power,,,No,
18,Power Generation,India,50.00%,No,
19,Company Limited,,,No,
20,Dahej SEZ Limited\nSpecial Economic Zone,India,50.00%,No,
21,Indradhanush Gas Grid,,,No,
22,Pipeline,India,20.00%,No,